In [211]:
import pandas as pd
import numpy as np

In [212]:
df1 = pd.read_csv('../data/train.csv')
df1

,user_id,course_id
0,5bdecbfffec014002166796a,5f194354cad0d086f3ee24cf
1,5fedf958af850a915c86362c,5bfd47782d018e0020e4b0e4 5fc4a352d375951a03cc0...
2,5fd255c43136a460c6f3f930,598053e0acc137070007186a 6031136edd9bc1681035b892
3,5a0bde2aa15b3f001e98429a,5fc5ed671be929537e5283bb 5fc5edae001c9102feab8...
4,5fedf8132a0eb0bfab27882b,5e8e9d3c5a140c3d1e1c5245
...,...,...
59732,6114c700aa04ce00067265a5,61034f3d4ef8b500067afc1c
59733,60e66f29be3e3b0006c4db75,55ae208a7b4d9910001198f2
59734,60e2b05ee742c300072ff5b3,600538ff0cf6c91168243a88
59735,60da0995947dfc0fb61ef296,5edf464fb54d0f59f0e7d96a
59736,5fd5ea567642a9ec30c89643,5a2170d5a6d4a5001ec3148d 5b9d3a6dca498a001e917383

In [213]:
df2 = pd.read_csv('../data/users.csv')
df2

,user_id,gender,occupation_titles,interests,recreation_names
0,54ccaa73a784960a00948687,female,NaN,"職場技能_創業,藝術_電腦繪圖,設計_介面設計,設計_動態設計,設計_平面設計,投資理財_投...",NaN
1,54dca4456d7d350900e86bae,male,NaN,"設計_動態設計,設計_平面設計,設計_應用設計,程式_程式入門,程式_程式語言,藝術_角色設...",NaN
2,54e421bac5c9c00900cd8d47,female,NaN,"設計_平面設計,職場技能_資料彙整,藝術_繪畫與插畫,行銷_數位行銷,職場技能_文書處理,職...",NaN
3,54e961d4c5c9c00900cd8d84,other,金融業,"投資理財_理財,攝影_影像創作,投資理財_投資觀念,藝術_更多藝術,音樂_樂器,投資理財_金...",NaN
4,54e9b744c5c9c00900cd8d8a,other,"資訊科技,法律、社會及文化專業,非營利組織","程式_網頁前端,投資理財_理財,投資理財_投資觀念,程式_程式語言,設計_設計理論,投資理財...","政治經濟,社會服務,舞台劇,電影"
...,...,...,...,...,...
130561,62e09de8fc3d3500060d4211,female,NaN,"語言_英文,設計_介面設計,設計_網頁設計,設計_設計理論,程式_軟體程式開發與維護,行銷_...",NaN
130562,62f0823a8c4414000667c592,NaN,NaN,NaN,NaN
130563,631b86242145060007efc7dd,NaN,NaN,NaN,NaN
130564,6331648104ed0f000610dfd2,male,公務人員,"投資理財_理財,攝影_影像創作,攝影_後製剪輯,攝影_商業攝影,投資理財_投資觀念","旅行旅遊,運動健身,金融理財,電影"
130565,6358a7599c01ba344812d24d,male,"服務業,其他","音樂_人聲,藝術_手寫字,藝術_色彩學,藝術_電腦繪圖,生活品味_靈性發展,藝術_素描,生活...","瑜珈,舞蹈,貓派"

In [214]:
merged = pd.merge(df1,df2,how='left',on=['user_id'])
merged

,user_id,course_id,gender,occupation_titles,interests,recreation_names
0,5bdecbfffec014002166796a,5f194354cad0d086f3ee24cf,female,服務業,"職場技能_創業,設計_平面設計,藝術_電腦繪圖,藝術_繪畫與插畫,手作_刺繡,攝影_影像創作...","手作,插畫,插花,水彩"
1,5fedf958af850a915c86362c,5bfd47782d018e0020e4b0e4 5fc4a352d375951a03cc0...,female,科技業,"投資理財_理財,攝影_動態攝影,攝影_影視創作,語言_英文,攝影_影像創作,攝影_後製剪輯","旅行旅遊,桌遊,運動健身,金融理財"
2,5fd255c43136a460c6f3f930,598053e0acc137070007186a 6031136edd9bc1681035b892,male,科技業,"生活品味_寵物,語言_日文,投資理財_理財,語言_英文,語言_韓文,職場技能_文書處理,職場...","貓派,金融理財,閱讀,電玩,電視劇"
3,5a0bde2aa15b3f001e98429a,5fc5ed671be929537e5283bb 5fc5edae001c9102feab8...,female,"出版業,資訊科技,其他","人文_文學,行銷_數位行銷,人文_社會科學,人文_更多人文,設計_平面設計","占卜,手寫字,手遊,貓派,閱讀,電影"
4,5fedf8132a0eb0bfab27882b,5e8e9d3c5a140c3d1e1c5245,male,服務業,"手作_更多手作,藝術_更多藝術","手遊,電玩"
...,...,...,...,...,...,...
59732,6114c700aa04ce00067265a5,61034f3d4ef8b500067afc1c,female,NaN,"語言_歐洲語言,職場技能_求職,投資理財_理財,攝影_動態攝影,投資理財_投資觀念,職場技能...",NaN
59733,60e66f29be3e3b0006c4db75,55ae208a7b4d9910001198f2,female,NaN,"手作_刺繡,生活品味_寵物,人文_文學,投資理財_理財,生活品味_運動,設計_平面設計,手作...",NaN
59734,60e2b05ee742c300072ff5b3,600538ff0cf6c91168243a88,male,製造業,"生活品味_寵物,生活品味_運動,藝術_手寫字,藝術_色彩學,設計_應用設計,職場技能_個人品...","插花,旅行旅遊,瑜珈,美容妝髮,運動健身,閱讀"
59735,60da0995947dfc0fb61ef296,5edf464fb54d0f59f0e7d96a,female,"藝文設計,服務業,自由業","手作_氣球,設計_更多設計,音樂_DJ,投資理財_比特幣,手作_刺繡,生活品味_寵物,人文_...","區塊鏈,占卜,寫作,手作,手寫字,手遊,插畫,插花,政治經濟,旅行旅遊,桌遊,棋類遊戲,水彩..."
59736,5fd5ea567642a9ec30c89643,5a2170d5a6d4a5001ec3148d 5b9d3a6dca498a001e917383,male,NaN,"投資理財_量化交易,投資理財_理財,投資理財_投資觀念,投資理財_金融商品,投資理財_更多投資理財",區塊鏈

In [215]:
df3 = merged[['user_id', 'course_id', 'interests']].dropna()
df3

,user_id,course_id,interests
0,5bdecbfffec014002166796a,5f194354cad0d086f3ee24cf,"職場技能_創業,設計_平面設計,藝術_電腦繪圖,藝術_繪畫與插畫,手作_刺繡,攝影_影像創作..."
1,5fedf958af850a915c86362c,5bfd47782d018e0020e4b0e4 5fc4a352d375951a03cc0...,"投資理財_理財,攝影_動態攝影,攝影_影視創作,語言_英文,攝影_影像創作,攝影_後製剪輯"
2,5fd255c43136a460c6f3f930,598053e0acc137070007186a 6031136edd9bc1681035b892,"生活品味_寵物,語言_日文,投資理財_理財,語言_英文,語言_韓文,職場技能_文書處理,職場..."
3,5a0bde2aa15b3f001e98429a,5fc5ed671be929537e5283bb 5fc5edae001c9102feab8...,"人文_文學,行銷_數位行銷,人文_社會科學,人文_更多人文,設計_平面設計"
4,5fedf8132a0eb0bfab27882b,5e8e9d3c5a140c3d1e1c5245,"手作_更多手作,藝術_更多藝術"
...,...,...,...
59732,6114c700aa04ce00067265a5,61034f3d4ef8b500067afc1c,"語言_歐洲語言,職場技能_求職,投資理財_理財,攝影_動態攝影,投資理財_投資觀念,職場技能..."
59733,60e66f29be3e3b0006c4db75,55ae208a7b4d9910001198f2,"手作_刺繡,生活品味_寵物,人文_文學,投資理財_理財,生活品味_運動,設計_平面設計,手作..."
59734,60e2b05ee742c300072ff5b3,600538ff0cf6c91168243a88,"生活品味_寵物,生活品味_運動,藝術_手寫字,藝術_色彩學,設計_應用設計,職場技能_個人品..."
59735,60da0995947dfc0fb61ef296,5edf464fb54d0f59f0e7d96a,"手作_氣球,設計_更多設計,音樂_DJ,投資理財_比特幣,手作_刺繡,生活品味_寵物,人文_..."
59736,5fd5ea567642a9ec30c89643,5a2170d5a6d4a5001ec3148d 5b9d3a6dca498a001e917383,"投資理財_量化交易,投資理財_理財,投資理財_投資觀念,投資理財_金融商品,投資理財_更多投資理財"

In [216]:
subgroup_csv = pd.read_csv('../data/subgroups.csv')
subgroup_csv

    subgroup_id subgroup_name
0             1        更多生活品味
1             2       護膚保養與化妝
2             3          平面設計
3             4         繪畫與插畫
4             5          電腦繪圖
..          ...           ...
86           87          數據分析
87           88            翻譯
88           89            模型
89           90          更多攝影
90           91          更多行銷

[91 rows x 2 columns]

In [217]:
courses_csv = pd.read_csv('../data/courses.csv').fillna('')
courses_csv[['course_id', 'sub_groups', 'groups+subgroups']][:20]

                   course_id      sub_groups               groups+subgroups
0   61888e868f154b000781b45a  更多生活品味,護膚保養與化妝       生活品味_更多生活品味,生活品味_護膚保養與化妝
1   54d5a117065a7e0e00725ac0      平面設計,繪畫與插畫               設計_平面設計,藝術_繪畫與插畫
2   54d5d9952246e60a009ec571       平面設計,電腦繪圖                設計_平面設計,藝術_電腦繪圖
3   54d7148a2246e60a009ec588  平面設計,應用設計,電腦繪圖        設計_平面設計,設計_應用設計,藝術_電腦繪圖
4   5513e92b38239d10005778e1           求職,英文                  語言_英文,職場技能_求職
5   55307d94d530a90a00a3a896            手作小物                        手作_手作小物
6   551a6be023774e0a001eb20c           繪畫與插畫                       藝術_繪畫與插畫
7   551171a938239d1000577864         DJ,更多音樂                  音樂_DJ,音樂_更多音樂
8   54f1268f4ec3c809002e4a29            更多藝術                        藝術_更多藝術
9   55599687dfe21b0a00e776d9         烹飪料理與甜點                   生活品味_烹飪料理與甜點
10  559e49185850311000fca504  壓力舒緩,更多生活品味,運動  生活品味_壓力舒緩,生活品味_更多生活品味,生活品味_運動
11  55a4d6397b4d99100011957d         烹飪料理與甜點                   生活品味_烹飪料理與甜點
12  55ae208a7b4d9910001198f2     更多生活品味,親子教育          生活品味_更多生活品味,生活品味_親子教育
13  55b0ba667b4d991000119a92              運動                        生活品味_運動
14  557ad62bd736230f00adb2ab            手工印刷                        手作_手工印刷
15  556ad58777a8710900bedffe             手工書                         手作_手工書
16  55ae36c87b4d99100011990f              運動                        生活品味_運動
17  55ae34247b4d99100011990d              運動                        生活品味_運動
18  55ae66017b4d991000119959              運動                        生活品味_運動
19  5591501e6dec460f00111314           繪畫與插畫                       藝術_繪畫與插畫

In [218]:
bought_course_onehot = np.zeros((len(df3), len(subgroup_csv)))
bought_course_onehot.shape

(59714, 91)

In [219]:
course_err = []
for i, course_lst in enumerate(df3['course_id']):
    for course in course_lst.split(' '):
        course_sub = courses_csv.loc[courses_csv['course_id'] == course, 'sub_groups'].iloc[0]
        #print(course, subgroup, end=' ')
        if(course_sub == ''):
            continue
        for sub in course_sub.split(','):
            try:
                #print(subgroup_csv.loc[subgroup_csv['subgroup_name'] == sub, 'subgroup_id'].iloc[0], end=' ')
                #print(label_column[i])
                bought_course_onehot[i][subgroup_csv.loc[subgroup_csv['subgroup_name'] == sub, 'subgroup_id'].iloc[0] - 1] = 1
            except IndexError:
                if(sub not in course_err):
                    course_err.append(sub)
print(bought_course_onehot)
print(course_err)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
['比特幣', '篆刻']

In [220]:
bought_course_onehot[-1, :]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [221]:
subgroup_dict = {}
for i, sub_name in enumerate(subgroup_csv['subgroup_name']):
    subgroup_dict[sub_name] = i+1
subgroup_dict

{'更多生活品味': 1,
 '護膚保養與化妝': 2,
 '平面設計': 3,
 '繪畫與插畫': 4,
 '電腦繪圖': 5,
 '應用設計': 6,
 '求職': 7,
 '英文': 8,
 '手作小物': 9,
 'DJ': 10,
 '更多音樂': 11,
 '更多藝術': 12,
 '烹飪料理與甜點': 13,
 '壓力舒緩': 14,
 '運動': 15,
 '親子教育': 16,
 '手工印刷': 17,
 '手工書': 18,
 '動態攝影': 19,
 '素描': 20,
 '樂器': 21,
 '色彩學': 22,
 '字體設計': 23,
 '手寫字': 24,
 '動態設計': 25,
 '音樂理論': 26,
 '刺繡': 27,
 '日文': 28,
 '心靈成長與教育': 29,
 '音樂創作': 30,
 '氣球': 31,
 '程式入門': 32,
 '程式語言': 33,
 '網頁前端': 34,
 '文書處理': 35,
 '角色設計': 36,
 '資料彙整': 37,
 '介面設計': 38,
 '網頁設計': 39,
 '商業攝影': 40,
 '網站架設': 41,
 '更多程式': 42,
 '程式思維': 43,
 '手機程式開發': 44,
 '韓文': 45,
 '更多手作': 46,
 '更多語言': 47,
 '歐洲語言': 48,
 '人聲': 49,
 '個人品牌經營': 50,
 '更多職場技能': 51,
 '網頁後端': 52,
 '後製剪輯': 53,
 '產品設計': 54,
 '靈性發展': 55,
 '影視創作': 56,
 '資料科學': 57,
 '軟體程式開發與維護': 58,
 '職場溝通': 59,
 '表演藝術': 60,
 '創業': 61,
 '文學': 62,
 '區塊鏈': 63,
 '金融商品': 64,
 '文案': 65,
 '數位行銷': 66,
 '設計理論': 67,
 'AI 人工智慧': 68,
 '投資觀念': 69,
 '理財': 70,
 '社會科學': 71,
 '社群行銷': 72,
 '影像創作': 73,
 '遊戲開發': 74,
 '程式理財': 75,
 '量化交易': 76,
 '更多設計': 77,
 '獨立接案': 78,
 '寵物': 79,
 '資訊安全': 80,
 '量化分析': 81,
 '數學': 82,
 '效率提升': 83,
 '居家': 84,
 '更多人文': 85,
 '攝影理論': 86,
 '數據分析': 87,
 '翻譯': 88,
 '模型': 89,
 '更多攝影': 90,
 '更多行銷': 91}

In [222]:
self_interest_onehot = np.zeros((len(df3), len(subgroup_csv)))

In [223]:
interest_err = []
for i, interest_lst in enumerate(df3['interests']):
    for interest in interest_lst.split(','):
        interest_sub = interest.split('_')[1]
        try:
            self_interest_onehot[i][subgroup_dict[interest_sub] - 1] = 1
        except KeyError:
            if(interest_sub not in interest_err):
                interest_err.append(interest_sub)
print(self_interest_onehot)
print(interest_err)

[[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 1. 1.]
 [0. 0. 0. ... 0. 0. 0.]]
['更多投資理財', '篆刻', '西班牙文', '比特幣']

In [224]:
self_interest_onehot[-1,]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

## user_id, input, label
user_id, self filled interest from user.csv, bought courses records from train.csv

57914, 57914 * 91, 57914 * 91

In [225]:
data = {'user_id': df3['user_id'].to_numpy(), 'input': self_interest_onehot, 'label': bought_course_onehot}
data

{'user_id': array(['5bdecbfffec014002166796a', '5fedf958af850a915c86362c',
        '5fd255c43136a460c6f3f930', ..., '60e2b05ee742c300072ff5b3',
        '60da0995947dfc0fb61ef296', '5fd5ea567642a9ec30c89643'],
       dtype=object),
 'input': array([[0., 0., 1., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 1., 1., ..., 0., 0., 0.],
        [1., 1., 1., ..., 0., 1., 1.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 'label': array([[0., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])}